import type { AddressInfo } from 'node:net';
import { extname, join, normalize, resolve, sep } from 'node:path';

/**
 * The window loads `app://mirrorbase/…`, a privileged custom scheme served by the main process:
 * the Angular build from disk, `/api/…` proxied to the in-process API on its random loopback
 * port. Same origin for both — no CORS, the app's `apiBaseUrl` stays empty — and a **stable**
 * origin across starts, so localStorage (theme, …) survives although the port changes.
 */
export const APP_SCHEME = 'app';
export const APP_HOST = 'mirrorbase';
export const APP_ORIGIN = `${APP_SCHEME}://${APP_HOST}`;

/**
 * Strict CSP for the window. Only own files; `style-src 'unsafe-inline'` because Angular and the
 * spartan components set style attributes; no `unsafe-eval`, no remote hosts — the desktop app
 * loads nothing from the network (database servers are reached by the API, not by the page).
 */
export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-src 'none'",
  "frame-ancestors 'none'",
].join('; ');

/** The runtime configuration the web app reads before it boots (see apps/web/public/env.js). */
export const DESKTOP_ENV_JS = `// Generated by the desktop app (apps/desktop). The API is on the same origin (app://).
window.__MB_ENV__ = {
  apiBaseUrl: '',
};
`;

const CONTENT_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
};

export function contentTypeOf(file: string): string {
  return (
    CONTENT_TYPES[extname(file).toLowerCase()] ?? 'application/octet-stream'
  );
}

export type Route =
  | { kind: 'api'; path: string }
  | { kind: 'env' }
  | { kind: 'file'; file: string }
  | { kind: 'index' }
  | { kind: 'forbidden' };

/**
 * What a request for `app://mirrorbase<pathname>` is: the API, the generated env.js, a file of the
 * web build, or the SPA's index.html (any other path without a file extension — Angular routes).
 * Never a file outside `webRoot` (`..`, encoded or not).
 */
export function routeRequest(
  pathname: string,
  webRoot: string,
  exists: (file: string) => boolean,
): Route {
  let decoded: string;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    return { kind: 'forbidden' };
  }
  if (decoded.includes('\0')) return { kind: 'forbidden' };
  if (decoded === '/api' || decoded.startsWith('/api/')) {
    return { kind: 'api', path: pathname };
  }
  if (decoded === '/env.js') return { kind: 'env' };
  if (decoded === '/' || decoded === '') return { kind: 'index' };

  const root = resolve(webRoot);
  const file = resolve(join(root, normalize(decoded)));
  if (file !== root && !file.startsWith(root + sep))
    return { kind: 'forbidden' };
  if (exists(file)) return { kind: 'file', file };
  // A missing asset is a 404, a deep link (no extension) the app shell.
  return extname(decoded) === '' ? { kind: 'index' } : { kind: 'forbidden' };
}

/** Request headers that must not be forwarded to the API (hop-by-hop, or set by the proxy). */
const DROPPED_REQUEST_HEADERS = new Set([
  'host',
  'origin',
  'referer',
  'connection',
  'keep-alive',
  'transfer-encoding',
  'upgrade',
  'cookie',
]);

export function forwardHeaders(
  incoming: Iterable<[string, string]>,
  accessHeader: string,
  accessToken: string,
): Record<string, string> {
  const headers: Record<string, string> = {};
  for (const [name, value] of incoming) {
    const lower = name.toLowerCase();
    if (!DROPPED_REQUEST_HEADERS.has(lower) && lower !== accessHeader) {
      headers[lower] = value;
    }
  }
  headers[accessHeader] = accessToken;
  return headers;
}

/** The port a server bound to (the OS's choice for `listen(0)`). */
export function boundPort(address: AddressInfo | string | null): number {
  if (!address || typeof address === 'string' || address.port <= 0) {
    throw new Error(`The API did not report a TCP port (${String(address)})`);
  }
  return address.port;
}
